model:
  backbone: gazenet

data:
  root: /home/lunet/cowz2/Documents/GazeEstimation/Dataset/GazeUnconstrained/processed_dataset

train:
  batch_size: 256
  epochs: 60
  lr: 0.00001
  step_size: 10
  gamma: 0.5

save:
  dir: ./checkpoints/gazenet
